# Site settings
title: Sauhard Shrestha
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  yada yada yada somehting cool to go here
   

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

email_address: sauahrd192@gmail.com
instagram_username: sauhard.stha
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
